//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADX.Entities.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class MailTemplate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MailTemplate()
        {
            this.NotificationByUsers = new HashSet<NotificationByUser>();
            this.UserNotifications = new HashSet<UserNotification>();
        }
    
        public string Id { get; set; }
        public string Body { get; set; }
        public string Subject { get; set; }
        public string Description { get; set; }
        public string SMSText { get; set; }
        public string Name { get; set; }
        public bool UserCanModify { get; set; }
        public string SmsTextType { get; set; }
        public bool VisibleToDealer { get; set; }
        public bool VisibleToInspector { get; set; }
        public bool BccToAccountManager { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NotificationByUser> NotificationByUsers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserNotification> UserNotifications { get; set; }
    }
}
