//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADX.Entities.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NotificationByUser
    {
        public string UserId { get; set; }
        public string MailTemplateId { get; set; }
        public bool ByEmail { get; set; }
        public bool ByMobile { get; set; }
        public bool BySMS { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MailTemplate MailTemplate { get; set; }
    }
}
