//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADX.Entities.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter
    {
        public string Id { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public string DefaultValue { get; set; }
        public string Description { get; set; }
        public string Name { get; set; }
        public short TypeCode { get; set; }
        public string Value { get; set; }
    }
}
