//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ADX.Entities.DomainModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserNotification
    {
        public int Id { get; set; }
        public string Attachments { get; set; }
        public bool ByEmail { get; set; }
        public bool BySMS { get; set; }
        public string DisplayName { get; set; }
        public string Email { get; set; }
        public string EmailBody { get; set; }
        public string EmailSubject { get; set; }
        public string Mobile { get; set; }
        public string SMSText { get; set; }
        public string TemplateId { get; set; }
        public string UserId { get; set; }
        public System.DateTimeOffset CreatedAt { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual MailTemplate MailTemplate { get; set; }
    }
}
